# Generated by Django 5.0.6 on 2025-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
