# Generated by Django 5.0.6 on 2025-08-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employeee_salary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeee',
            new_name='Employee',
        ),
    ]
